layout_spectrum: 0.20933044818229973
typography_spectrum: 0.5591075869742781
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.5520603063050658
  lightness: 0.5743787800893188
  saturation: 0.06709940801374614
  rhythmicContrast: 0.8429378815926611
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Sk.de
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Suchen
    url: 'http://www.google.de'
    type: external
  - name: Logics bunte Bl√∂cke
    id: e5a75bfe-5287-41ee-8567-627091841ab0
    type: content
favicon: null
title: Tagline? Hugh?
description: Whats this?
purpose: []
